#!/bin/bash -x

tc qdisc show dev ifb0
tc qdisc del dev ifb0 root
tc qdisc show dev ifb0
# créer les classes 1:1, 1:2, 1:3, pour les classes de trafic 0, 1 et 2
sudo tc qdisc add dev ifb0 root handle 1: prio
tc qdisc show dev ifb0
sudo tc qdisc add dev ifb0 parent 1:1 handle 10: sfq
sudo tc qdisc add dev ifb0 parent 1:2 handle 20: tbf rate 200mbit burst 10000 limit 10000
sudo tc qdisc add dev ifb0 parent 1:3 handle 30: tbf rate 50mbit burst 10000 limit 10000
tc qdisc show dev ifb0
tc filter add dev ifb0 parent 1:0 protocol ip prio 1 u32 match ip tos 0x10 0xff flowid 1:1
tc filter add dev ifb0 parent 1:0 protocol ip prio 3 u32 match ip tos 0x08 0xff flowid 1:3
